# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0db3efd93e55b439de19eefdf92e515dfa8b4a89499bef2b2fbbf44165316a3b351fbb7ab106e3688f9a7111a006d932268588036f454a4c11c3ba8fe659a6c3

test:
  secret_key_base: 5d36516277662ffac2d0d92325447dd62f83857b7ef7ac500e965ce0fc5bc877445490049ab298a9c4cc7bc42e0419bf18de379a1d45fbd51734962f2d45fb65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
